//
//  TeamNames.swift
//  FootballAgent
//
//  Created by Rodolfo Antoniazzi on 17/04/24.
//

import Foundation

class TeamNames {
    
    static let firstName : [String] = [
    "Manchester",
    "London",
    "Paris",
    "Wrexham",
    "Stockholm",
    "Madrid",
    "Barcelona",
    "Lisboa",
    "Porto",
    "Valencia",
    "Cadiz",
    "Bilbao",
    "Salamanca",
    "León",
    "Málaga",
    "Córdoba",
    "Gibraltar",
    "Badajoz",
    "Coimbra",
    "Andorra",
    "Bordeaux",
    "Marseille",
    "Nice",
    "Lyon",
    "Versailles",
    "Brest",
    "Brussels",
    "Amsterdam",
    "Rotterdam",
    "Cardiff",
    "Bristol",
    "Reading",
    "Oxford",
    "Southampton",
    "Exeter",
    "Cambridge",
    "Norwich",
    "Sheffild",
    "Liverpool",
    "Leeds",
    "Hull",
    "Glasgow",
    "Edimburgh",
    "Belfast",
    "Dublin",
    "Cork",
    "Galway",
    "Ghent",
    "Dortmund",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Munich",
    "Ulm",
    "Vienna",
    "Prague",
    "Berlin",
    "Hamburg",
    "Leipzig",
    "São Paulo",
    "Buenos Aires",
    "Porto Alegre",
    "Copenhagen",
    "Warsaw",
    "Oslo",
    "Belo Horizonte",
    "New York",
    "San Francisco",
    "Los Angeles",
    "Seattle",
    "Phoenix",
    "San Antonio",
    "Orlando",
    "Miami",
    "Atlanta",
    "Washington",
    "Philadelphia",
    "Chicago",
    "Bogotá",
    "Quito",
    "Lima",
    "Santiago",
    "Rio de Janeiro"
    ]
    
    static let seccondName : [String] = [
    "Reds",
    "Blues",
    "Greens",
    "Yellows",
    "Blacks",
    "Whites",
    "United",
    "Atletic",
    "Union",
    "Royals",
    "Football",
    "Club",
    "International",
    "National",
    "Sporting",
    "Rangers",
    "Rapid",
    "City",
    "Saints",
    "Deportivo",
    "Villa",
    "Greatests",
    "Students",
    "Wolves",
    "Lions",
    "Warriors",
    "Raiders",
    "Eagles",
    "Elephants",
    "Tigers",
    "Snakes",
    "Spiders",
    "Wildcats",
    "Knights",
    "Panthers",
    "Falcons",
    "Chargers",
    "Dolphins",
    "Titans",
    "Trojans",
    "Devils",
    "Beavers",
    "Mammoths",
    "Marauders",
    "Jaguars",
    "Bears",
    "Avengers",
    "Saints",
    "Vikings",
    "Bees",
    "Buccaneers",
    "Terriers",
    "Tornadoes",
    "Cobras"
    ]
    
    static func createName() -> String {
        return "\(firstName[Int.random(in: 0...firstName.count-1)]) \(seccondName[Int.random(in: 0...seccondName.count-1)])"
    }
}
